# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Gandalf',
            field=models.ManyToManyField(to='app.Book'),
        ),
    ]
