# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_gandalf'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Silmarils',
            field=models.ManyToManyField(to='app.Chapter'),
        ),
    ]
